/**
 * SOMAKID AI - Mock Library Data
 * Placeholder digital books until the real Library backend exists.
 */

import type { Book } from '../../types/education.types';

export const BOOKS: Book[] = [
  {
    id: 'book_contes_baobab',
    title: 'Les Contes du Baobab',
    author: 'Collectif SOMAKID',
    coverEmoji: '📖',
    color: '#C0722A',
    category: 'story',
    description: "Un recueil de contes traditionnels africains pour petits et grands, transmis de génération en génération.",
    pages: 48,
    isPremium: false,
    language: 'fr',
    readingLevel: 'early',
  },
  {
    id: 'book_kimia_foret',
    title: 'Kimia et la Forêt Enchantée',
    author: 'Aline Nzuzi',
    coverEmoji: '🌳',
    color: '#2D9B6E',
    category: 'story',
    description: "Kimia part à l'aventure dans la forêt du Congo et découvre des animaux extraordinaires.",
    pages: 32,
    isPremium: false,
    language: 'fr',
    readingLevel: 'early',
  },
  {
    id: 'book_animaux_afrique',
    title: "Le Grand Livre des Animaux d'Afrique",
    author: 'Dr Emmanuel Tshibangu',
    coverEmoji: '🦓',
    color: '#F4A228',
    category: 'science',
    description: 'Un guide illustré richement documenté sur la faune du continent africain.',
    pages: 96,
    isPremium: true,
    language: 'fr',
    readingLevel: 'independent',
  },
  {
    id: 'book_comprendre_climat',
    title: 'Comprendre le Climat en Images',
    author: 'Collectif SOMAKID',
    coverEmoji: '🌦️',
    color: '#1B6CA8',
    category: 'science',
    description: 'Le changement climatique expliqué simplement, avec des schémas et des exemples locaux.',
    pages: 40,
    isPremium: false,
    language: 'fr',
    readingLevel: 'independent',
  },
  {
    id: 'book_petits_gestes',
    title: 'Petits Gestes, Grande Planète',
    author: 'Grace Ilunga',
    coverEmoji: '🌱',
    color: '#38A169',
    category: 'science',
    description: 'De petites actions quotidiennes que chaque enfant peut faire pour protéger la planète.',
    pages: 28,
    isPremium: false,
    language: 'fr',
    readingLevel: 'early',
  },
  {
    id: 'book_poemes_terre',
    title: 'Poèmes pour la Terre',
    author: 'Josée Mbayo',
    coverEmoji: '🌸',
    color: '#EC4899',
    category: 'poetry',
    description: 'Un recueil de poèmes célébrant la nature et la beauté du continent africain.',
    pages: 24,
    isPremium: true,
    language: 'fr',
    readingLevel: 'independent',
  },
  {
    id: 'book_bien_manger',
    title: 'Bien Manger, Bien Grandir',
    author: 'Dr Sarah Beya',
    coverEmoji: '🥗',
    color: '#E8921A',
    category: 'health',
    description: 'Les bases de la nutrition expliquées aux enfants avec des recettes locales et équilibrées.',
    pages: 36,
    isPremium: false,
    language: 'fr',
    readingLevel: 'early',
  },
  {
    id: 'book_grandir_sante',
    title: 'Grandir en Bonne Santé',
    author: 'Dr Sarah Beya',
    coverEmoji: '💪',
    color: '#8B5CF6',
    category: 'health',
    description: "Un guide complet sur la santé et le bien-être, pensé pour accompagner les préadolescents.",
    pages: 64,
    isPremium: true,
    language: 'fr',
    readingLevel: 'advanced',
  },
];
